import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/ui/header";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import "reflect-metadata";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <AntdRegistry>
            <header>
              <Header />
            </header>
            <main className={"min-h-screen"}>{children}</main>
            <footer>footer</footer>
          </AntdRegistry>
        </NextUIProvider>
      </body>
    </html>
  );
}
